server.port=8080

spring.datasource.url=jdbc:sqlite:alerts.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.com.csa.pricealert=DEBUG
logging.level.org.springframework.web.socket=INFO

# Binance WSS
binance.websocket.url=wss://stream.binance.com:443/ws/!ticker@arr
